import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

abstract class AppIcon {
  static const IconData language = Icons.language;
  static const IconData circle = Icons.circle_outlined;
  static const IconData notifcation = FontAwesomeIcons.bell;
  static const IconData solidChessRook = FontAwesomeIcons.barsStaggered;
  static const IconData cart = FontAwesomeIcons.cartShopping;
  static const IconData bagShopping = FontAwesomeIcons.bagShopping;
  static const IconData search = FontAwesomeIcons.magnifyingGlass;
  static const IconData home = FontAwesomeIcons.house;
  static const IconData favoriteSolid = FontAwesomeIcons.solidHeart;
  static const IconData favorite = FontAwesomeIcons.heart;
  static const IconData profile = FontAwesomeIcons.solidUser;
  static const IconData star = FontAwesomeIcons.star;
  static const IconData solidStar = FontAwesomeIcons.solidStar;
  static const IconData starHalf = FontAwesomeIcons.starHalfStroke;
  static const IconData plus = FontAwesomeIcons.plus;
  static const IconData minus = FontAwesomeIcons.minus;
  static const IconData arrowLeft = FontAwesomeIcons.arrowLeftLong;
  static const IconData arrowRight = FontAwesomeIcons.arrowRightLong;
  static const IconData settings = FontAwesomeIcons.gear;
  static const IconData signOut = FontAwesomeIcons.arrowRightFromBracket;
  static const IconData about = FontAwesomeIcons.circleInfo;
  static const IconData xmark = FontAwesomeIcons.xmark;
  static const IconData trash = FontAwesomeIcons.trash;
  static const IconData notExpand = FontAwesomeIcons.sortDown;
  static const IconData expand = FontAwesomeIcons.sortUp;
  static const IconData angleRight = FontAwesomeIcons.angleRight;
  static const IconData angleLeft = FontAwesomeIcons.angleLeft;
  static const IconData lightMode = FontAwesomeIcons.moon;
  static const IconData darkMode = FontAwesomeIcons.solidMoon;
  static const IconData email = FontAwesomeIcons.envelope;
  static const IconData password = FontAwesomeIcons.lock;
  static const IconData eye = FontAwesomeIcons.solidEye;
  static const IconData eyeLock = FontAwesomeIcons.solidEyeSlash;
  static const IconData userEdit = FontAwesomeIcons.userPen;
  static const IconData editImage = FontAwesomeIcons.solidPenToSquare;
}
